// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import * as path from "path";

// Electron 进程类型扩展
type ElectronProcess = NodeJS.Process & {
  resourcesPath?: string;
};

// 判断是否在 Electron 打包环境
const electronProcess = process as ElectronProcess;
const isElectronPackaged = typeof electronProcess.resourcesPath !== 'undefined';

// 获取数据库路径
const getDatabaseUrl = (): string => {
  if (process.env["DATABASE_URL"]) {
    return process.env["DATABASE_URL"];
  }

  // Electron 打包后，数据库在 resources/database/ 目录
  if (isElectronPackaged && electronProcess.resourcesPath) {
    return `file:${path.join(electronProcess.resourcesPath, "database", "app.db")}`;
  }

  // 开发环境，数据库在 electron/app-data/database/ 目录
  return "file:./electron/app-data/database/app.db";
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
